### ISSUE TITLE
Ability to see error responses when erroring.

### ISSUE THREAD

**Issue by PeterTheMango** [Majored/mcm-js-api-wrapper#2]
So currently whenever we work with the api on our bot when the package throws an error it doesn't really tell you much about what the error is and where it came from. Would be nice if it could show the json response of why it errored out so that it would make it easier for us developers to fix it.

**Comment by Majored** [comment]
You'd need to call .toString() on the error at current ([impl](https://github.com/MC-Market-org/js-api-wrapper/blob/main/src/Error.js#:~:text=*/-,toString,-()%20%7B)).

There isn't any way to override the prototype toString() within a class definition (to my understanding), so that's why this doesn't happen automatically when say logging to console.

I'll go ahead and close this as this functionality is already present (just with added indirection which we may resolve down the line).
